#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Thu Oct 08 17:25:59 GMT 2026
android.nonTransitiveRClass=true
kapt.include.compile.classpath=false
org.gradle.daemon.idletimeout=10800000
systemProp.user.language=en
systemProp.user.country=US
kapt.use.worker.api=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8
android.useAndroidX=true
kapt.use.k2=true
kotlin.code.style=official
kapt.incremental.apt=false
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
android.builder.sdkDownload=true
android.enableR8.fullMode=false
